quotes = [
    '"Herb is the healing of a nation, alcohol is the destruction." ― Bob Marley',
    '"When you smoke the herb, it reveals you to yourself." ― Bob Marley'
    '"Why is marijuana against the law? It grows naturally upon our planet. Doesn’t the idea of making nature against the law seem to you a bit . . . unnatural?" ― Bill Hicks',
    '"We all need something to help us unwind at the end of the day. You might have a glass of wine, or a joint, or a big delicious blob of heroin to silence your silly brainbox of its witterings but there has to be some form of punctuation, or life just seems utterly relentless." ― Russell Brand, My Booky Wook',
    '"Federal and state laws (should) be changed to no longer make it a crime to possess marijuana for private use." ― Richard Nixon',
    '"The amount of money and of legal energy being given to prosecute hundreds of thousands of Americans who are caught with a few ounces of marijuana in their jeans simply makes no sense - the kindest way to put it. A sterner way to put it is that it is an outrage, an imposition on basic civil liberties and on the reasonable expenditure of social energy." ― William F. Buckley',
    '"Is marijuana addictive? Yes, in the sense that most of the really pleasant things in life are worth endlessly repeating." ― Richard Neville',
    '"So when he asked about getting high, I didn\'t think, I agreed. We smoked some good California green. Took three tries to put me in the place he said I should be." ― Ellen Hopkins',
    '"Marijuana enhances our mind in a way that enables us to take a different perspective from \'high up\', to see and evaluate our own lives and the lives of others in a privileged way. Maybe this euphoric and elevating feeling of the ability to step outside the box and to look at life’s patterns from this high perspective is the inspiration behind the slang term “high” itself." ― Sebastian Marincolo',
    '"And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat." ― Anonymous, Holy Bible: King James Version',
    '"The legalization of marijuana is not a dangerous experiment – the prohibition is the experiment, and it has failed dramatically, with millions of victims all around the world." ― Sebastian Marincolo ',
    '"The drug war is a total scam, prescription drugs kill 300K a year, while marijuana kills no one, but they spend billions/year \'fighting\' it, because pot heads make for good little slaves to put into private prisons, owned by the banks who launder the drug money, and it\'s ALL DOCUMENTED." ― Alex E. Jones',
    '"To inspire himself, he lit up a marijuana cigarette, excellent Land-O-Smiles brand." ― Philip K. Dick, The Man in the High Castle ',
    '"It’s strange that munchies are a real thing, but they are. He knows why, though. THC binds with smell receptors." ― A.D. Aliwat, In Limbo',
    '"Unquestionably, this drug is is very useful to the artist, activating trains of association that would otherwise be inaccessible, and I owe many of the scenes in Naked Lunch directly to the use of cannabis." ― William Burroughs',
    '"Cannabis is just way too healthy for a sick health care system" ― Sebastian Marincolo',
    '"Marijuana should be legalized. All drugs should be legalized. I\'m tired of all the best party people being caged." ― Thor Benson',
    '"I think that marijuana should not only be legal, I think it should be a cottage industry. There’s some pretty good homegrown dope. I’m sure it would be even better if you could grow it with fertilizers and have greenhouses." ― Stephen King ',
    '"Marijuana is fuel for a creative mind. Fuck this prohibition." ― A.K. Kuykendall ',
    '"Banning something is the easiest way to make it desirable." ― Tapan Ghosh, Faceless The Only Way Out',
    '"When you smoke the herb, it reveals you to yourself." — Bob Marley',
    '"I know you’re supposed to tell kids not to do drugs, but, kids, do it! Do weed! Don’t do the other stuff, but weed is good!" — Kevin Smith',
    '"Everything is better with a bag of weed." — Stewie Griffin',
    '"Struggle is the enemy, but weed is the remedy." — Kid Cudi"When I was a kid I inhaled frequently. That was the point." —Barack Obama',
    '"When I was a kid I inhaled frequently. That was the point." — Barack Obama',
    '"That is not a drug, it’s a leaf." — Arnold Schwarzenegger',
    '"If you ain’t got a good job and you ain’t smokin’ weed, then I dont know what the f--- you are doin’ with your life?" — Katt Williams',
    '"Smoking marijuana, as long as you leave the nicotine out of it, is certainly no more damaging than having a drink, and I suspect better for you than having a drink." — Richard Branson',
    '"Alcohol and marijuana, if used in moderation, plus loud, usually low-class music, make stress and boredom infinitely more bearable." — Kurt Vonnegut',
    '"Hemp is of first necessity to the wealth & protection of the country." — Thomas Jefferson',
    '"Instead of taking five or six of the prescriptions, I decided to go the natural route and smoke marijuana." — Melissa Etheridge',
    '"Even if one doesn’t smoke pot one has to see the benefits of decriminalizing it!" — Danny Devito',
    '"Of course I know how to roll a joint." — Martha Stewart',
    '"Marijuana is not a drug! I used to suck dick for coke! You ever suck dick for marijuana?" — Bob Saget',
    '"I think pot should be legal. I don’t smoke it, but I like the smell of it." — Andy Warhol',
    '"I’d always done a lot of sniffing glue as a kid. I was very interested in glue, and then I went to lager and speed, and I drifted into heroin because as a kid growing up everybody told me, ‘don’t smoke marijuana, it will kill you.’" — Irvine Welsh',
    '"I smoked pot in college, and in the Army…" — Al Gore',
    '"I hope they legalize marijuana and when they do I’ll be the first fucking person in line to buy my pack of joints." — Megan Fox',
    '"I don’t consider weed to be any worse than having a beer." — James Franco',
    '"It really puzzles me to see marijuana connected with narcotics… dope and all that crap. It’s a thousand times better than whiskey—it’s an assistant—a friend." — Louis Armstrong',
    '"Prison is for rapists, thieves, and murderers. If you lock someone up for smoking a plant that makes them happy, then you’re the fucking criminal." — Joe Rogan',
    '"A friend with weed is a friend indeed." — Pops O’Donnell',
    '"I definitely believe marijuana helps with menstruation. Since I started smoking pot, my girlfriend’s period has become painless for me." — Randy Kagan TC mark',
    '"If you substitute marijuana for tobacco and alcohol, you’ll add eight to 24 years to your life." — Jack Herer',
    '"A marijuana high can enhance core human mental abilities." — Sebastian Marincolo',
    '"Don’t kill the high because you are low, Don’t."',
    '"By regulating marijuana, we can put black market drug dealers out of business and eliminate the rebellious allure that attracts young people." — Sal Albanese',
    '"Don’t judge someone until you have shared a joint with them."',
    '"If somebody gives me a joint, I might smoke it, but I don’t go after it." — John Lennon',
    '"If you want to smoke marijuana in your basement, I don’t care! I’m not going to get a search warrant and kick your door in. I think that’s foolish." — Bill O’Reilly',
    '"Let us burn one from end to end, and pass it over to me my friend." — Ben Harper',
    '"Smoke the marijuana and get high. Stay above the wicked and fly." — Snoop Dogg',
    '"They’ve outlawed the No. 1 vegetable on the planet." — Timothy Leary',
    '"To make marijuana against the law is like saying God made a big mistake." — Bill Hicks',
    '"You know you’re a stoner when your friends make you a Bob Marley cake." — Miley Cyrus',
    '"Please don’t throw your shit at me…unless that shit resembles a bag of marijuana." — Les Claypool',
    '"So what if I’m smoking weed onstage and doing what I gotta do? It’s not me shooting nobody, stabbing nobody, killing nobody. It’s a peaceful gesture and they have to respect that and appreciate that." – Snoop Dogg',
    '"Smoking helped put me in touch with the realm of the senses." – Hugh Hefner',
    '"If somebody’s gonna smoke a joint… And not do anybody else any harm. Then perhaps there are other things that our cops should be looking at." – Sarah Palin',
    '"The illegality of cannabis is outrageous, an impediment to full utilization of a drug which helps to produce serenity and insight, sensitivity and fellowship so desperately needed in this increasingly mad and dangerous world." – Carl Sagan',
    '"It is beyond my comprehension that any humane person would withhold such a beneficial substance from people in such great need simply because others use it for different purposes." – Steven Gould',
    '"I apprehended the structure of certain pieces of jazz and classical music in a new manner under the influence of marijuana, and these apprehensions have remained valid in years of normal consciousness." – Allen Ginsberg',
    '"I wake up early in the morning and it feels so good. Smoking on some shit that you wish you could." – Snoop Dogg',
    '"When you smoke marijuana, you are in the moment and you are happy. You forget about any worries of the past or the future." – Tommy Chong',
    '"Marijuana has killed far fewer people than swimming pools; it’s the war against it that does all the violence." – Lawrence Reed',
    '"The weed is for the people. It’s the people’s weed." – Jonah Hill',
    '"More than anything, the weed really helped with my mental state, because marijuana works on the brain. And if anything, it soothes the brain." – Tommy Chong',
    '"Sativa to change the things I can, Indica to accept the things I can\'t."',
    '"Marijuana may not be addictive, but growing it is." – Ed Rosenthal',
    '"In our culture, the Native Americans, when two strangers come together. You know what we do in our culture? We smoke the peace pipe." – Tatanka',
    '"Roll, roll, roll a joint and pass it down the line. Take a toke, inhale the smoke and blow your f*cking mind!"',
    '"Next to making a proper omelette or wiping your own ass, rolling a joint is an essential life skill for any self-respecting member of society." – Anthony Bourdain"',
    '"They lie about marijuana, tell you pot-smoking makes you unmotivated. LIE! When you’re high, you can do everything you normally do, just as well. You just realize that it’s not worth the fucking effort. There is a difference." - Bill Hicks',
    '"Marijuana prohibition is just the stupidest law possible. Just legalize it and tax it like we do liquor." – Morgan Freeman',
    '"The biggest killer on the planet is stress, and I still think that the best medicine is and always has been cannabis." – Willie Nelson',
    '"I find it quite ironic that the most dangerous thing about weed is getting caught with it." – Bill Murray'
]
